# --- Basic Site Settings ---
locale: "en-US"
title: "Jun's Homepage"
title_separator: "-"
name: &name "Jun Jiang"
description: &description "Jun's academic portfolio"
url: "https://junjiangw6c6.github.io"
baseurl: ""
repository: "junjiangw6c6/junjiangw6c6.github.io"

# academicpages / Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Author (Minimal Mistakes expects images/* by default)
author:
  avatar: "/images/headshot.png"   # note the leading slash + images/
  name: "Jun Jiang"
  pronouns: "she/her"
  bio: "A PhD student, a fluffy admirer, and a plant lover"
  location: "New Haven"
  employer: "Yale University, School of the Environment"
  email: "jun.jiang@yale.edu"
  #googlescholar: "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  #orcid: ""                         # leave blank or put your real ORCID URL
  #pubmed: ""                        # remove placeholder that points to 'john snow'
  researchgate: "https://www.researchgate.net/profile/Jun-Jiang-77"
  github: "junjiangw6c6"
  linkedin: "jun-jiang-urban-health"                      # add if you want

# Publication categories (kept as you had them)
publication_category:
  books:        { title: "Books" }
  manuscripts:  { title: "Journal Articles" }
  conferences:  { title: "Conference Papers" }

# Site Settings
teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json*
  - README
  - tmp
  - vendor
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# Kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults for layouts
defaults:
  - scope: { path: "", type: posts }
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope: { path: "", type: pages }
    values:
      layout: single
      author_profile: true
  - scope: { path: "", type: teaching }
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope: { path: "", type: publications }
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope: { path: "", type: portfolio }
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope: { path: "", type: talks }
    values:
      layout: talk
      author_profile: true
      share: true

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins (GitHub Pages–compatible)
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives (optional)
category_archive: { type: liquid, path: /categories/ }
tag_archive:      { type: liquid, path: /tags/ }

# HTML Compression (optional)
compress_html:
  clippings: all
  ignore:
    envs: development
